FROM debian:stable
RUN apt-get update && apt-get install -y gnupg2

# dart
RUN apt-get install -y apt-transport-https wget
RUN wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list
RUN apt-get update
RUN apt-get install -y dart
RUN dart pub global activate sass
ENV PATH $PATH:/root/.pub-cache/bin

WORKDIR /var/www/html